import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function ContactForm() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [mobile, setMobile] = useState();
  const [date, setDate] = useState();

  const handleSubmit = (e) => {
    e.preventDefault();
    const data = {
      name,
      mobile,
      email,
      message,
      dete,
    };
    console.log(data);
  };

  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main>
        <form onSubmit={handleSubmit} className={styles.form}>
          <label htmlFor="name">שם מלא:</label>
          <input
            id="name"
            type="text"
            onChange={(e) => setName(e.target.value)}
          />
          <label htmlFor="mobile">נייד:</label>
          <input
            id="mobile"
            type="num"
            onChange={(e) => setMobile(e.target.value)}
          />
          <label htmlFor="mobile">תאריך:</label>

          <input
            id="date"
            type="num"
            onChange={(e) => setDate(e.target.value)}
          />
          <label htmlFor="email">דואר אלקטורני:</label>
          <input
            id="email"
            type="email"
            onChange={(e) => setEmail(e.target.value)}
          />
          <label htmlFor="message">הודעה:</label>
          <textarea
            id="message"
            type="text"
            rows="4"
            onChange={(e) => setMessage(e.target.value)}
          />
          <button type="submit">אישור</button>
        </form>
      </main>
    </div>
  );
}
console.log();
