import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Carousel from "nuka-carousel";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lioras Designs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpeg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ליאורה עיצובים
          {/* <a href="https://nextjs.org">Next.js!</a> */}
        </h1>

        <p className={styles.description}>
          חלום של ילד <code className={styles.code}></code>
        </p>

        <div>
          <Carousel wrapAround={true} slidesToShow={8} autoplay={1000}>
            <Image
              src="/images/3H2A3286.jpg"
              alt="pic"
              width={250}
              height={350}
            />
            <Image
              src="/images/3H2A3424.jpg"
              alt="pic"
              width={250}
              height={350}
            />
            <Image
              src="/images/3H2A3499-1.jpg"
              alt="pic"
              width={250}
              height={350}
            />
            <Image
              src="/images/20211211_105931.jpg"
              alt="pic"
              width={250}
              height={350}
            />
            <Image
              src="/images/DSC_4751.JPG"
              alt="pic"
              width={250}
              height={350}
            />
          </Carousel>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link href="../AboutMe">
          <a className={styles.logo}>
            {" "}
            קצת עלי {"  "}
            <Image src="/icon.jpeg" alt="Logo" width={100} height={100} />
          </a>
        </Link>
      </footer>
    </div>
  );
}
